---
title: "dag"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dag}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bdb2021)
library(tidyverse)
library(ggdag)
```

```{r}
pick_play_dag <-
  ggdag::dagify(
  epa ~ pick_play,
  epa ~ epa_predictors,
  pick_play ~ epa_predictors,
  epa ~ pass_defenders,
  epa ~ player_coverage,
  epa ~ team_coverage,
  epa ~ offense_skill,
  epa ~ defense_skill,
  pick_play ~ wp,
  exposure = 'pick_play',
  outcome = 'epa',
  labels = c(
    'pick_play' = 'Pick Play',
    'epa' = 'EPA',
    'epa_predictors' = 'EPA Predictors',
    'pass_defenders' = '# of Pass Defenders',
    'team_coverage' = 'Team Coverage',
    'player_coverage' = 'Player Coverage',
    'wp' = 'Win Probability'
  )
)
pick_play_dag %>% ggdag::ggdag()
pick_play_dag %>% ggdag::ggdag_paths()
```

```{r}
pick_play_epa_dag <-
  dagitty::dagitty()
pick_play_epa_dag %>% 
  dag_paths(paths_only = FALSE) %>% 
  ggplot(aes(x = x, y = y, xend = xend, yend = yend, col = path, alpha = path)) +
  geom_dag_edges_link(
    aes(
      edge_alpha = path, 
      edge_colour = path,
      start_cap = ggraph::circle(3, 'mm'), 
      end_cap = ggraph::circle(3, 'mm')
    )
  ) +
  geom_dag_point(size = 4) + 
  facet_wrap(~forcats::fct_inorder(as.factor(set), ordered = TRUE)) +
  scale_alpha_manual(
    drop = FALSE, 
    values = c("open path" = 1), 
    na.value = .35, 
    breaks = "open path"
  ) +
  ggraph::scale_edge_alpha_manual(
    drop = FALSE, 
    values = c("open path" = 1), 
    na.value = .35, 
    breaks = "open path"
  ) +
  ggraph::scale_edge_colour_hue(drop = FALSE, breaks = "open path") +
  scale_color_hue(drop = FALSE, breaks = "open path") +
  expand_plot(
    expand_x = expansion(c(0.25, 0.25)),
    expand_y = expansion(c(0.1, 0.1))
  ) + 
  theme(legend.position = "none")
```
