---
title: 'Using presaved data'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{using_presaved_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bdb2021)
library(tidyverse)
```

```{r}
data('receiver_intersections_relaxed', package = 'bdb2021')
data('closest_defenders', package = 'bdb2021')
data('personnel_and_rushers', package = 'bdb2021')
receiver_intersections_relaxed
closest_defenders
personnel_and_rushers
```

Let's try to answer the question "Did pick plays have higher EPA than other pass plays?"

```{r}
plays <- import_plays()
# pbp <- 
#   import_nflfastr_pbp() # %>% 
#   # select(game_id = old_game_id, play_id, wpa, epa) %>% 
#   # mutate(across(c(game_id, play_id), as.integer))
# pbp

pick_play_meta_init <-
  receiver_intersections_relaxed %>% 
  filter(has_intersection) %>% 
  unnest(intersection) %>% 
  distinct(week, game_id, play_id, sec_end = sec, nfl_id, nfl_id_intersect) %>% 
  # Data should be dropped with this join because we are only joining on one `sec` interval per play and `y_side`.
  inner_join(
    pick_play_ids_adj,
    by = c('game_id', 'play_id', 'nfl_id', 'nfl_id_intersect', 'sec_end')
  ) %>% 
  relocate(.data$sec_start, .data$sec_end, .after = dplyr::last_col()) %>% 
  # Just get the `target_nfl_id` first.
  inner_join(
    plays %>% 
      select(game_id, play_id, target_nfl_id), 
    by = c('game_id', 'play_id')
  ) %>% 
  group_by(game_id, play_id, nfl_id, nfl_id_intersect, sec_start, sec_end) %>% 
  # There will be some NAs here due to missing `target_nfl_id`s.
  # I think it's best to leave these in.
  summarize(
    target_is_intersect = sum(target_nfl_id == nfl_id)
  ) %>% 
  ungroup()
pick_play_meta_init

plays_w_pick_info <-
  plays %>% 
  left_join(
    pick_play_meta_init %>% 
      nest(pick_play = -c(game_id, play_id)),
    by = c('game_id', 'play_id')
  ) %>% 
  left_join(
    personnel_and_rushers %>% 
      # Remove unneeded columns.
      # mutate(
      #   rushers = map(rushers, ~select(.x, nfl_id, dist_to_ball_abs, idx_closest_to_ball))
      # ),
      select(-rushers) %>% 
      rename(n_qb_rusher = n_qb),
    by = c('game_id', 'play_id')
  ) %>% 
  mutate(
    is_pick_play = map_lgl(pick_play, ~!is.null(.x)), 
    across(n_rusher, ~coalesce(.x, 0L)),
    # pick_play = map_if(pick_play, is.null, ~tibble())
  ) %>% 
  relocate(week, game_id, play_id, is_pick_play, pick_play)
plays_w_pick_info
plays_w_pick_info %>% filter(!is_pick_play)

pick_play_meta <-
  pick_play_meta_init %>% 
  # Now get other numbers from `plays`.
  inner_join(
    plays %>% 
      select(game_id, play_id, pass_result, epa, possession_team, quarter, down, yards_to_go), 
    by = c('game_id', 'play_id')
  ) %>% 
  left_join(
    pbp %>% rename(wpa_nflfastr = wpa, epa_nflfastr = epa),
    by = c('game_id', 'play_id')
  )
pick_play_meta
```

```{r}
data('nflfastr_epa_model_features', package = 'bdb2021')
nflfastr_epa_model_features

```

"Did pick plays have higher EPA when one of the intersection receivers was targeted?"

```{r}
pick_play_meta %>% 
  # Drop the plays where the targeted receiver is NA.
  drop_na() %>% 
  # mutate(across(pass_result, ~if_else(.x, != 'C', 'I', .x))) %>% 
  count(target_is_intersect, sec_start, sec_end, pass_result) %>% 
  filter(pass_result == 'C') %>% 
  group_by(target_is_intersect) %>% 
  mutate(frac = n / sum(n)) %>% 
  ungroup()

pick_play_agg <-
  pick_play_meta %>% 
  # Drop the plays where the targeted receiver is NA.
  drop_na() %>% 
  mutate(across(pass_result, ~if_else(.x != 'C', 'I', .x))) %>% 
  group_by(target_is_intersect, sec_start, sec_end, pass_result) %>% 
  summarize(
    n = n(),
    across(c(ends_with('_nflfastr'), epa), mean)
  ) %>% 
  ungroup() # %>% 
  # group_by(target_is_intersect, sec_start, sec_end) %>% 
  # mutate(frac = n / sum(n)) %>% 
  # ungroup()
pick_play_agg

viz <-
  pick_play_agg %>% 
  unite(sec_bin, sec_start, sec_end, sep = '-') %>% 
  mutate(
    across(target_is_intersect, ~if_else(.x == 0, 'no', 'yes') %>% factor())
  ) %>% 
  pivot_longer(-c(target_is_intersect, sec_bin, pass_result)) %>% 
  ggplot() +
  aes(x = sec_bin, y = value) +
  geom_col(aes(group = target_is_intersect, fill = target_is_intersect), position = 'dodge') +
  facet_grid(name~pass_result, scales = 'free_y') +
  theme_minimal() +
  theme(legend.position = 'top') +
  labs(x = NULL, y = NULL)
viz
```

```{r}

pick_play_ids_adj
pick_plays %>% filter(sec == max(sec))
# No adjusted intersections between 3 and 3.5 seconds.
pick_play_ids_adj %>% filter(sec_end == max(sec_end))

pick_play_n <-
  pick_play_ids_adj %>% 
  inner_join(plays %>% select(game_id, play_id, epa)) %>% 
  group_by(.data$week, .data$sec_start, .data$sec_end) %>%
  summarize(
    across(.data$n_intersection, sum),
    across(.data$epa, mean)
  ) %>% 
  ungroup() %>% 
  arrange(.data$week, .data$sec_start, .data$sec_end) %>% 
  group_by(.data$week) %>% 
  mutate(
    across(.data$n_intersection, list(cumu = cumsum)),
    across(.data$epa, list(cumu = cummean))
  ) %>% 
  ungroup() %>% 
  group_by(.data$sec_start, .data$sec_end) %>% 
  summarize(
    across(starts_with('n_intersection'), sum),
    across(starts_with('epa'), mean)
  ) %>% 
  ungroup()
pick_play_n
pick_plays %>% count(game_id, play_id, sort = TRUE)

normal_play_ids <-
  pick_plays %>% 
  filter(!has_intersection) %>% 
  distinct(week, game_id, play_id, y_side_init, n_route)
normal_play_ids

normal_plays_agg <-
  normal_play_ids %>% 
  inner_join(plays %>% select(game_id, play_id, epa)) %>% 
  summarize(
    n = n(),
    across(.data$epa, mean)
  ) %>% 
  ungroup()
normal_plays_agg
```

Who ran the most pick plays? (TODO: Add seconds grouping here.)

```{r}
pick_play_meta %>% 
  count(team = possession_team, sort = TRUE)
```
